Default: &defaults
  user: yesodcms
  password: yesodcms
  host: localhost
  port: 5432
  database: yesodcms
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yesodcms_test
  <<: *defaults

Staging:
  database: yesodcms_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesodcms_production
  poolsize: 100
  <<: *defaults
