Default: &defaults
  host: "10.0.2.15"
  port: 3000
  connectionPoolSize: 10

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "ditadocs.content-lifecycle.com"
  port: 80
  connectionPoolSize: 100
