Default: &defaults
  host: "http://localhost"
  port: 3000
  connectionPoolSize: 10

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "http://beta.yesodweb.com"
  port: 5007
  connectionPoolSize: 10
