Default: &defaults
  host: "10.0.0.3"
  port: 3000
  connectionPoolSize: 10

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://socialkb.suite-sol.com"
  port: 5007
  connectionPoolSize: 10
